### ISSUE TITLE
Setup basic app using existing Datapub components

### ISSUE THREAD

**Issue by risenW** [datopian/gift-publisher#2]
Task

* [x] Getting started
  * [x] Boot a git repo: gift-publisher
  * [x] Start a new DataPub based project https://github.com/datopian/datapub#getting-started
* [x] Stub the basic "resource creator" flow (we already have this)
  * [x] file upload / link (note uploading won't be working for now because we don't have a backend)
  * [x] table schema editor

<img width="1283" alt="Screen Shot 2020-12-09 at 10 26 21 AM" src="https://user-images.githubusercontent.com/29900845/101610824-08b30a00-3a09-11eb-935e-977c00a3c8dc.png">

**Comment by sglavoie** [comment]
**FIXED**: Closing because all tasks were done.

* Issue #4 was created to take care of setting up GitHub Pages.
* The setup runs at https://datopian.github.io/gift-publisher/
