### ISSUE TITLE
Can't download Datapackage

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-publisher#40]
for dataset not having `datapackage.json` in its github repo, downloading of `data package` fails at the end of the publisher workflow (even when a resource is being uploaded). 

I don't know if this issue is meant to be fixed in  #36  but I made a suggestion of how I currently work through this in #39

**Comment by sglavoie** [comment]
FIXED: @risenW worked on this in #36 and left [this comment in #39](https://github.com/datopian/gift-publisher/pull/39#issuecomment-773317152):

> @steveoni This issue is caused by the refactor. I have fixed it in this current issue #36.
