### ISSUE TITLE
The `datapackage.json` file can be downloaded any number of times on the last screen of the publisher when clicking on "Download package"

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#43]
## Acceptance

* [x] The `datapackage.json` file can be downloaded any number of times on the last screen of the publisher when clicking on "Download package". – **DONE: This now works after merging #41**

## Tasks

* ...

## Analysis

* Filling out all the fields in the previous steps, clicking on "Download package" more than once shows the error `TypeError: Cannot read property 'fields' of undefined`. Same is true if the encoding is changed.
  * If one does not fill out all the fields (e.g., only fill one value per column in the CSV file from either "Title" or "Description") and leave the Rich Type field empty (or fill all the Rich Type fields and leave some of the "Title" and "Description" empty), the following error is generated when trying to download the package twice in a row: `TypeError: (intermediate value)(intermediate value).schema.fields.forEach is not a function`.

**Comment by risenW** [comment]
@estebanruseler I don't think we need this anymore, as download now works in #41

**Comment by estebanruseler** [comment]
@risenW did you mean to tag me? Maybe you meant @sglavoie instead?

**Comment by sglavoie** [comment]
@estebanruseler Sorry, this was a false alarm. :+1: 
@risenW Thank you, I can confirm it works. :slightly_smiling_face:

FIXED: Closing because the issue has been taken care of when merging #41. Just tested the flow at https://gift-portal-git-master.datopian1.vercel.app/ and it worked as expected.
