### ISSUE TITLE
Users should be able to add/remove a logo to a dataset

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#55]
* When I create a dataset, I want to be able to indicate the URL to an image for my dataset so I can show who it belongs to.
* When I edit the metadata of a dataset, I want to be able to remove a logo that has been shown previously (if a URL was entered) and either save my dataset without any logo or save my dataset with a new logo so I can leave my dataset in the state I prefer (i.e. updating or removing the URL for the `image` property).

## Acceptance

* [x] Users can add (when creating or editing), remove (when editing and no logo has been uploaded) and replace (when editing and logo has already been uploaded) a logo for a given dataset (i.e. by changing the URL value for the `image` property). **Done** See https://github.com/datopian/gift-publisher/pull/71 and image below:

<img width="1078" alt="Screen Shot 2021-03-19 at 11 11 23 AM" src="https://user-images.githubusercontent.com/29900845/111764928-0da71580-88a4-11eb-99b2-8e8dfda33643.png">

## Tasks

* [x] Add a field to the metadata for a dataset which is "image" URL (saved in `image` field on datapackage.json  https://specs.frictionlessdata.io/data-package/#image) and use that on dataset and home page.

## Analysis (current)

* We do not want to manage/store images for users. The images should be loaded from URLs instead.

## Analysis (outdated)

<details>

* A logo doesn't have to be uploaded when creating a dataset as the person publishing the dataset may not have the image at hand but may need to make data available regardless.
* A logo should be removable because the wrong logo could be uploaded or could need to be removed while a new one is on the way.
* A logo can be replaced when editing for the same reason as in the previous point: otherwise, the user would need to follow the flow, remove the logo, save the dataset and go back to editing to upload a new image instead of doing it in a single step (which is what would be expected, just like when someone updates a profile picture on a social network).
* The absence of a logo could literally be a transparent image filling the required space to guarantee that text remains aligned whether there is a logo or not.
* GIFT and their users want to see the owner of datasets in the home page as well as in the dataset page.

</details>

**Comment by risenW** [comment]
@sglavoie I updated and split this issue into two, as some changes will be done in Portal.  Find the second part here https://github.com/datopian/gift-portal/issues/165

**Comment by sglavoie** [comment]
@risenW Thank you, that's good. :slightly_smiling_face:  :+1:
