### ISSUE TITLE
[Research] Analyze how much work will be involved in porting the validation rules from `os-packager` to validate the "rich types"

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-publisher#82]
When I publish a dataset with the GIFT Publisher, I want the tool to automatically apply validation rules (the same we had in [OpenSpending Packager](https://github.com/openspending/os-packager)) so that I can more reliably generate a valid data package (i.e. the output is standardized thanks to applying validation rules).

## Acceptance

* [x] We have a good estimate on much effort would be required to port the existing validation code from `os-packager` over to GIFT Publisher to validate the "rich types". – **DONE: It will take approximately 2 days work.**

* If the estimate is reasonable, this should then be implemented (open a new issue).

## Tasks

* [x] Investigate how much effort it would take to port the validation code for the "rich types" from `os-packager` so that the GIFT Publisher uses those validation rules when creating a dataset and forces the user to enter a valid type for each column. – **DONE: See [comment below](https://github.com/datopian/gift-publisher/issues/82#issuecomment-833382322) for details.**

## Analysis

At this time, GIFT Publisher validates the schema for resources, but no validation happens for the "rich types". We need to track down where the code that took care of that in the OpenSpending Packager resides. A possible starting point could be here: https://github.com/openspending/os-packager/blob/6b08421f30ebe404d45f331141e76d296a321a6e/app/front/scripts/services/validation.js

This repo should contain the answer as this is the part of the OpenSpending infrastructure that is responsible for packaging a dataset and for letting the user upload it to the platform.

We need to figure out where this validation code is exactly. For instance, the following mappings with the "rich types" should not be possible because the first field is of type year and the second field is an ID, so the chosen value should be rejected by the publisher when clicking "Next".

![2021-05-04_10-50](https://user-images.githubusercontent.com/32682903/117034570-12475200-acc9-11eb-88c3-728b9a47c5ac.png)

The details of how this should work can be left as part of another (new) issue but for now, it is needed to investigate how much effort will be required to port over the code responsible for the validation of those rich types.

**Comment by risenW** [comment]
@sglavoie I did some in-depth research, and below is my conclusion:

I don't think Open spending is validating rich types. If you look at this [function](https://github.com/openspending/os-packager/blob/6b08421f30ebe404d45f331141e76d296a321a6e/app/services/package.js#L108) where a fiscal data package was generated, they are making a call to os-types [fieldsToModel](https://github.com/openspending/os-types/blob/77e0d2a72e05544e45e9f3c5cd4cb94965b93a47/src/index.js#L273) function. This function (fieldsToModel) is responsible for converting resource fields into FDP format, but if you check the validation function it's calling ([_validinput](https://github.com/openspending/os-types/blob/77e0d2a72e05544e45e9f3c5cd4cb94965b93a47/src/index.js#L118)), it is not actually validating the rich types, just the structure and properties of the field object. 

 If we are to do this, then we might have to write our own validator. Writing our validator will take approximately 2 days work.

**Comment by sglavoie** [comment]
Thank you very much @risenW! I will have to update you later internally at Datopian as Google services are down on my end at the moment (even Gmail and google.com!).

**Comment by sglavoie** [comment]
FIXED: Tasks done in this issue. We have a good time estimate (approx. 2 days) on the actual work required to port the validation rules from OpenSpending.

Work to be done in #85
